In [25]:
#! pip install seaborn

In [26]:
import numpy as np
import pandas as pd
import seaborn as sns

In [27]:
titanic = sns.load_dataset('titanic')
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [28]:
titanic = titanic[['survived', 'sex', 'pclass', 'age']]
titanic

survived     sex  pclass   age
0           0    male       3  22.0
1           1  female       1  38.0
2           1  female       3  26.0
3           1  female       1  35.0
4           0    male       3  35.0
..        ...     ...     ...   ...
886         0    male       2  27.0
887         1  female       1  19.0
888         0  female       3   NaN
889         1    male       1  26.0
890         0    male       3  32.0

[891 rows x 4 columns]

In [29]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   sex       891 non-null    object 
 2   pclass    891 non-null    int64  
 3   age       714 non-null    float64
dtypes: float64(1), int64(2), object(1)
memory usage: 28.0+ KB


In [30]:
titanic.dropna(axis=0, inplace=True)
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 714 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  714 non-null    int64  
 1   sex       714 non-null    object 
 2   pclass    714 non-null    int64  
 3   age       714 non-null    float64
dtypes: float64(1), int64(2), object(1)
memory usage: 27.9+ KB


C:\Users\orsys\AppData\Local\Temp\ipykernel_14224\3297023833.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  titanic.dropna(axis=0, inplace=True)


In [31]:
titanic['sex'].replace(['male', 'female'], [0, 1], inplace=True)
titanic

C:\Users\orsys\AppData\Local\Temp\ipykernel_14224\12809590.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  titanic['sex'].replace(['male', 'female'], [0, 1], inplace=True)


survived  sex  pclass   age
0           0    0       3  22.0
1           1    1       1  38.0
2           1    1       3  26.0
3           1    1       1  35.0
4           0    0       3  35.0
..        ...  ...     ...   ...
885         0    1       3  39.0
886         0    0       2  27.0
887         1    1       1  19.0
889         1    0       1  26.0
890         0    0       3  32.0

[714 rows x 4 columns]

In [32]:
y = titanic['survived']
X = titanic.drop(['survived'], axis=1)

In [33]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(X, y)
model.score(X, y)

0.8417366946778712

In [49]:
def has_survived(model,pclass=3,sex=0,age=47):
    x = np.array([pclass,sex,age]).reshape(1,3)
    print(np.array([pclass,sex,age]))
    print(x)
    return model.predict(x)

p = has_survived(model,pclass=2,sex=0,age=38)

[ 2  0 38]
[[ 2  0 38]]


C:\Users\orsys\Desktop\Formation\tp12\venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [50]:
p

array([1], dtype=int64)